#!/usr/bin/env node

/**
 * WordPress local environment setup script.
 *
 * Starts WordPress Playground CLI, waits for it to be ready,
 * reads the auto-generated Application Password, and updates
 * wp-bridge.config.ts with the credentials.
 *
 * Usage: node scripts/wp-setup.mjs
 */

import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const WP_SITE_DIR = resolve(ROOT, "wordpress/site");
const PASSWORD_FILE = resolve(WP_SITE_DIR, "wp-content/astro-cms-connect-app-password.txt");
const LOGIN_PASSWORD_FILE = resolve(WP_SITE_DIR, "wp-content/astro-cms-connect-login-password.txt");
const CONFIG_FILE = resolve(ROOT, "wp-bridge.config.ts");
const PORT = 8888;
const WP_URL = `http://127.0.0.1:${PORT}`;

/**
 * Wait for WordPress to respond on the given URL.
 */
async function waitForWordPress(url, maxRetries = 30) {
	for (let i = 0; i < maxRetries; i++) {
		try {
			const res = await fetch(`${url}/wp-json/`, {
				signal: AbortSignal.timeout(3000),
				redirect: "follow",
			});
			if (res.ok) return true;
		} catch {
			// Not ready yet.
		}
		console.log(`  Waiting for WordPress... (${i + 1}/${maxRetries})`);
		await new Promise((r) => setTimeout(r, 2000));
	}
	return false;
}

/**
 * Read the Application Password generated by the blueprint.
 */
function readAppPassword() {
	if (!existsSync(PASSWORD_FILE)) {
		return null;
	}
	return readFileSync(PASSWORD_FILE, "utf-8").trim();
}

/**
 * Read the randomised admin login password generated by the blueprint.
 */
function readLoginPassword() {
	if (!existsSync(LOGIN_PASSWORD_FILE)) {
		return null;
	}
	return readFileSync(LOGIN_PASSWORD_FILE, "utf-8").trim();
}

/**
 * Update wp-bridge.config.ts with the Application Password and (optionally)
 * the admin login password. Only the first `password:` occurrence is treated
 * as the Application Password; the `loginPassword:` key is matched explicitly.
 */
function updateConfig(password, loginPassword) {
	if (!existsSync(CONFIG_FILE)) {
		console.error("  wp-bridge.config.ts not found.");
		return false;
	}

	let content = readFileSync(CONFIG_FILE, "utf-8");
	content = content.replace(
		/password:\s*"[^"]*"/,
		`password: "${password}"`,
	);
	if (loginPassword) {
		if (content.includes("loginPassword")) {
			content = content.replace(
				/loginPassword:\s*"[^"]*"/,
				`loginPassword: "${loginPassword}"`,
			);
		}
	}
	writeFileSync(CONFIG_FILE, content, "utf-8");
	return true;
}

/**
 * Main setup flow.
 */
async function main() {
	console.log("\n=== Astro CMS Connect Setup ===\n");

	// Ensure wordpress/site directory exists.
	if (!existsSync(WP_SITE_DIR)) {
		mkdirSync(WP_SITE_DIR, { recursive: true });
	}

	// Check if password already exists (WordPress was set up before).
	const existingPassword = readAppPassword();
	if (existingPassword) {
		console.log("  Application Password already exists.");
		console.log("  Updating wp-bridge.config.ts...");
		const existingLogin = readLoginPassword();
		if (updateConfig(existingPassword, existingLogin)) {
			console.log("  Config updated.\n");
			console.log(`  WordPress: ${WP_URL}/wp-admin`);
			if (existingLogin) {
				console.log(`  Login:     admin / ${existingLogin}`);
			}
			console.log(`  Astro:     npm run dev\n`);
		}
		console.log("  To start WordPress:");
		console.log(`  npx @wp-playground/cli@latest server \\`);
		console.log(`    --mount-before-install=${WP_SITE_DIR}:/wordpress \\`);
		console.log(`    --mount=./wordpress/plugins/astro-cms-connect:/wordpress/wp-content/plugins/astro-cms-connect \\`);
		console.log(`    --blueprint=blueprint.json \\`);
		console.log(`    --port=${PORT}\n`);
		return;
	}

	console.log("  Starting WordPress Playground CLI...\n");

	const isWindows = process.platform === "win32";

	const mountArgs = isWindows
		? [
				"--mount-before-install-dir", WP_SITE_DIR, "/wordpress",
				"--mount-dir", "./wordpress/plugins/astro-cms-connect", "/wordpress/wp-content/plugins/astro-cms-connect",
			]
		: [
				`--mount-before-install=${WP_SITE_DIR}:/wordpress`,
				"--mount=./wordpress/plugins/astro-cms-connect:/wordpress/wp-content/plugins/astro-cms-connect",
			];

	const wpProcess = spawn(
		"npx",
		[
			"@wp-playground/cli@latest",
			"server",
			...mountArgs,
			"--blueprint=blueprint.json",
			`--port=${PORT}`,
		],
		{
			cwd: ROOT,
			stdio: ["ignore", "pipe", "pipe"],
			shell: true,
		},
	);

	wpProcess.stdout.on("data", (data) => {
		const line = data.toString().trim();
		if (line) console.log(`  [WP] ${line}`);
	});

	wpProcess.stderr.on("data", (data) => {
		const line = data.toString().trim();
		if (line) console.log(`  [WP] ${line}`);
	});

	wpProcess.on("error", (err) => {
		console.error(`  Failed to start Playground CLI: ${err.message}`);
		console.error("  Make sure @wp-playground/cli is installed:");
		console.error("  npm install -g @wp-playground/cli");
		process.exit(1);
	});

	// Wait for WordPress to be ready.
	console.log(`  Waiting for WordPress at ${WP_URL}...`);
	const ready = await waitForWordPress(WP_URL);

	if (!ready) {
		console.error("  WordPress did not start in time. Check logs above.");
		wpProcess.kill();
		process.exit(1);
	}

	console.log("  WordPress is ready.\n");

	// Wait a moment for the blueprint runPHP step to complete.
	await new Promise((r) => setTimeout(r, 3000));

	// Read the generated Application Password.
	const password = readAppPassword();
	if (!password) {
		console.error("  Application Password file not found.");
		console.error(`  Expected at: ${PASSWORD_FILE}`);
		console.error("  The blueprint runPHP step may have failed.");
		wpProcess.kill();
		process.exit(1);
	}

	console.log("  Application Password created.");
	const loginPassword = readLoginPassword();
	console.log("  Updating wp-bridge.config.ts...");

	if (updateConfig(password, loginPassword)) {
		console.log("  Config updated.\n");
	}

	console.log("=== Setup Complete ===\n");
	console.log(`  WordPress: ${WP_URL}/wp-admin`);
	if (loginPassword) {
		console.log(`  Login:     admin / ${loginPassword}`);
		console.log(`  (also saved in wp-bridge.config.ts → auth.loginPassword)`);
	}
	console.log(`  Astro:     npm run dev`);
	console.log(`  Health:    ${WP_URL}/wp-json/cdx/v1/health\n`);
	console.log("  WordPress is running. Press Ctrl+C to stop.\n");

	// Keep running until user stops.
	process.on("SIGINT", () => {
		console.log("\n  Stopping WordPress...");
		wpProcess.kill();
		process.exit(0);
	});

	process.on("SIGTERM", () => {
		wpProcess.kill();
		process.exit(0);
	});
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
